# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ClickToTile
                                 A QGIS plugin
 Extracts clicked coordinates from the mouse
 Generated by Plugin Builder 3
 ***************************************************************************/
"""


def name():
    return "ClickToTile"


def description():
    return "Extracts clicked coordinates from the mouse"


def version():
    return "Version 1.0"


def classFactory(iface):
    from .click_to_tile import ClickToTile
    return ClickToTile(iface)


def qgisMinimumVersion():
    return "3.0"


def author():
    return "Your Name"


def email():
    return "your.email@example.com"
